#local
#service.host=http://localhost
#service.port=4111
#service.api.version=/api/v1
#frontend.url=http://frontend
#selenoid.url=http://localhost:4444/wd/hub

#remote
service.host=http://62.60.150.19
service.port=4111
service.api.version=/api/v1
frontend.url=http://62.60.150.19
selenoid.url=http://62.60.150.19:4444/wd/hub

selenoid.browser=chrome
selenoid.browser.size=1920x1080

log.http.enabled=true
log.testDuration.enabled=false

admin.username=admin
admin.password=admin