#local
service.host=http://localhost
service.port=4111
service.apiVersion=/api/v1
db.url=jdbc:postgresql://localhost:5432/nbank
db.login=postgres
db.password=postgres

#remote
#service.host=http://109.120.135.36
#service.port=4111
#service.apiVersion=/api/v1

selenoid.url=http://109.120.135.36:4444/wd/hub
selenoid.browser=chrome
selenoid.browserSize=1920x1080

log.http.enabled=true
log.testDuration.enabled=false

admin.username=admin
admin.password=admin