apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenoid-ui   # Название Deployment (kubectl get deployment selenoid-ui)
spec:
  replicas: 1   # Количество реплик
  selector:   # Селектор, который определяет, какими подами управляет этот Deployment
    matchLabels:
      app: selenoid-ui   # Ищем поды, у которых есть label 'app' со значением 'selenoid-ui'
  template:   # Шаблон для создания новых подов
    metadata:
      labels:
        app: selenoid-ui   # Метки, которые будут установлены на каждый созданный Pod (должны совпадать с selector.matchLabels)
    spec:
      containers:
        - name: selenoid-ui
          image: aerokube/selenoid-ui:latest
          args: ["--selenoid-uri", "http://selenoid:4444"]
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: selenoid-ui   # Название Service
spec:
  selector:
    app: selenoid-ui   # Селектор определяет, на какие поды будет направлять трафик этот Service
  ports:
    - protocol: TCP
      port: 8080   # Порт, на котором Service будет доступен внутри кластера
      targetPort: 8080   # Порт на целевом контейнере (внутри пода), куда Service будет перенаправлять трафик
  type: NodePort   # Тип Service'а. NodePort делает Service доступным снаружи кластера
